### PR TITLE
Designed Cart and Wishlist pages

### PR DESCRIPTION
**Pull request by shangkaul**
Screenshot 2022-02-13 at 10 00 45 PM
Screenshot 2022-02-13 at 10 00 53 PM

### CODE REVIEW

**Review by Krushna-Kulkarni — COMMENTED** [review]
Everything looks good to me.

**Review by parvez-rashid — COMMENTED** [review]
Looks good to merge.

**Review by manish-GH — CHANGES_REQUESTED** [review]
I don't think flex-wrap is doing what it's meant to do. You might change its parent style to width:100vw and give a max-width.

It might be just me but, the button hover color blue looks weird compared to the rest of the app. You can consider using a darker shade

**Comment by shangkaul** [comment]
> I don't think flex-wrap is doing what it's meant to do. You might change its parent style to width:100vw and give a max-width.
> 
> It might be just me but, the button hover color blue looks weird compared to the rest of the app. You can consider using a darker shade

Thanks for the input, yeah I still have to decide a color for the button hover. Not an issue since it's derived from a CSS variable, I'll change the variable value and it'll be reflected on the entire site.

**Pull request merged**
